id: P008003
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:54:28.848161
source_metadata:
  id: bdr:W2CZ7854
  title: སྔགས་རིམ་ཆེན་མོ།
  author: ''
  volumes:
    0936d215b4c84638884b6b3741254d7d:
      image_group_id: I1KG9240
      title: Volume 1 of sngags rim chen mo/
      volume_number: 1
      total_pages: 734
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
