id: P008003
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ7854
  title: སྔགས་རིམ་ཆེན་མོ།
  author: ''
  volumes:
    65e11f09024249eca6203d66a54f8a29:
      image_group_id: I1KG9240
      title: ''
      volume_number: 1
      total_pages: 734
ebook_metadata:
  title: སྔགས་རིམ་ཆེན་མོ།
  author: ''
  sku: P008003
  cover: cover.jpg
  layers:
  - pagination
